#!/bin/sh
xrdb -merge ~/.Xdefaults
# dvorak layout
setxkbmap -layout us,ru -variant 'dvp,' ,winkeys -option grp:caps_toggle,grp_led:scroll,terminate:ctrl_alt_bksp,compose:ralt
# key delay
xset r rate 200 50
# especially for NGS desktop
xrandr --output VGA-0 --left-of DVI-I-1

i3
